name: Deploy Angular Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      # 3. Install dependencies and Angular CLI
      - name: Install dependencies
        run: |
          npm install
          npm install -g @angular/cli@17
          
      # 4. Build Angular project
      - name: Build Angular project
        run: ng build

      # 5. Copy build files to EC2
      - name: Copy build files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "dist/**"
          target: "/var/www/test/angular_example/"
          script: sudo systemctl reload nginx
