name: Deploy Angular Frontend to EC2 using Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Install dependencies and build Angular app
      - name: Install & Build
        run: |
          npm install --force
          npm run build

      # 4️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # 5️⃣ Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/angular-frontend:latest .

      # 6️⃣ Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/angular-frontend:latest

      # 7️⃣ SSH into EC2 and deploy Docker container
      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USER }}/angular-frontend:latest
            docker stop angular-frontend || true
            docker rm angular-frontend || true
            docker run -d --name angular-frontend -p 80:80 ${{ secrets.DOCKER_USER }}/angular-frontend:latest
