name: Deploy Angular Frontend to EC2 using Docker
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install & Build
        run: |
          npm install --force
          npm run build

      - name: Docker Logout
        run: docker logout

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/angular-frontend:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/angular-frontend:latest

      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with: 
           host: ${{ secrets.EC2_HOST }}
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.EC2_KEY }}
           port: 22
           timeout: 60s
           script: |
              # Pull latest Docker image
              docker pull ${{ secrets.DOCKER_USER }}/angular-frontend:latest

              # Stop and remove existing container
              docker stop angular-frontend || true
              docker rm angular-frontend || true

              # Run container on port 8080 (avoid conflict with host Nginx)
              docker run -d --name angular-frontend -p 8080:80 ${{ secrets.DOCKER_USER }}/angular-frontend:latest
